### ISSUE TITLE
website breaks every time someone pushes any trivial change

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-lang.org#350]
Every time we push anything, the website breaks, and we have to manually hit the ultra-secret hidden back-door secret thing.

@emmanuelbernard you're the only one who really understands awestruct, would you be able to find time to take a look?

**Comment by FroMage** [comment]
Perhaps it's because of timeouts?

https://github.com/ceylon/ceylon-lang.org/settings/hooks/766437

**Comment by FroMage** [comment]
OK if I disable the hook from github and call that myself manyally it works, but takes a long time. I bet it timesout from github (they just don't wait) and that kills the rebuilding.

**Comment by FroMage** [comment]
OK I will leave the hook disabled for now since it just breaks everything. From now on use the force hook to update the website, OK?

Monday I will change it so that the hook is done asynchronously which will prevent any timeout, but I also want to put a protection in place so that we can't trigger two builds at the same time, which happens when we all hit the force hook at the same time, which also breaks things.

I don't want to make that change today before the weekend.

**Comment by emmanuelbernard** [comment]
Thanks @FroMage, you are correct, this is a timeout issue. I'm interested in how you will do the async work (me lurking).

**Comment by FroMage** [comment]
OK, webhook is fixed and much improved. More information by email since this issue is too open.
