### ISSUE TITLE
Update the Tour of Ceylon regarding function (un-)equality

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-lang.org#390]
Filed by @haumacher on https://github.com/ceylon/ceylon/issues/5872

https://github.com/ceylon/ceylon/issues/5594 breaks the example at http://ceylon-lang.org/documentation/1.2/tour/functions/:
```
interface Subscription {
    shared formal void cancel();
}
abstract class Component() {

    variable {Anything(Event)*} observers = {};

    shared Subscription addObserver(void observe(Event event)) {
        observers = {observe, *observers};
        object subscription satisfies Subscription {
            cancel() => observers = 
                    { for (o in observers) if (o!=observe) o };
        }
        return subscription;
    }

    shared void fire(Event event) {
        for (observe in observers) {
            observe(event);
        }
    }
}
```

The observer cancelation no longer works, since it depends on observer functions being comparable for equality.

**Comment by tombentley** [comment]
@gavinking I think you should fix this. Obviously we can use a box to fix those examples, but that requires us to explain the need for the box and thus we really need a whole little section on function equality. I'm sure I could write something, but I'm also sure you'd then end up rewriting it.

**Comment by gavinking** [comment]
fixed.

**Comment by haumacher** [comment]
@gavinking Don't you think that the tutorial wouldn't benefit from a word of wisdom / warning why the symmetric API (`addListener(l)`, `removeListener(l)`) for listener registration widely used in the Java world cannot be used when using pure functions as listeners in Ceylon? 

What about a Gotcha! section saying something like: 

> Did you notice that the `Subscription` type is still there even when being eliminated from the public API by using pure functions as listener and cancellation callbacks.  The `Subscription` type is internally necessary for listener management, because pure functions in Ceylon cannot be compared for equality. When storing the listener functions directly in the `subscriptions` list, a given function cannot be filtered from the list during cancellation, because it cannot be identified. This is also the reason, why the symmetric API for listener registration widlely used in the Java world (`addListener(l)`, `removeListener(l)`) is not applicable to Ceylong, when using pure functions as listeners. 

While writing this I recognize that even if the examples are fixed now, they are still misleading. In the first example using pure functions instead of listener interface instances, a function list `variable {Anything(Event)*} observers = {};` is still used for listener management. Even if this looks like the obvious solution, its a really bad example, because it cannot be extended to a real life solution. An API for listener registration without the possibility of unregistration is demo-only. But unregistering is not possible in principle, when storing pure functions without wrapping them first. At least a word of warning should be inserted to this example, too.

**Comment by gavinking** [comment]
@haumacher done!

**Comment by haumacher** [comment]
Cool :+1:
