### ISSUE TITLE
Incorrect statement in the Tour of Ceylon?

### ISSUE THREAD

**Issue by loldrup** [ceylon/ceylon-lang.org#483]
In the chapter named '[Inheritance, refinement and interfaces](https://www.ceylon-lang.org/documentation/1.3/tour/inheritance/#refinement)' in the Ceylon Tour it says:

"We can't inadvertently refine a member of the superclass"

I think the 'or' should be an 'of', but apart from this typo, I have my doubts as to whether this claim is true at all:

In the section hat follows ('[Shortcut syntax for refinement](https://www.ceylon-lang.org/documentation/1.3/tour/inheritance/#shortcut_syntax_for_refinement)') we are shown that members of a superclass can actually be refined by subclasses using the exact same syntax that one uses to define ordinary references and getters in classes. That ordinary syntax can, for instance, be seen in the section '[Abstracting state using attributes](https://www.ceylon-lang.org/documentation/1.3/tour/classes/#abstracting_state_using_attributes)' in the 'Classes' chapter of the Tour.

So, given the existence of the shortcut syntax, how would one know if one is just defining ordinary references and getters, or if one is inadvertently refining a member of some superclass in the inheritance hierarchy?

**Comment by lucaswerkmeister** [comment]
> think the 'or' should be an 'of', but apart from this typo

I don’t think that’s a typo – the sentence makes sense to me as it is. With “or”, it seems weird to me: we’re already refining the superclass!

> we are shown that members of a superclass can actually be refined by subclasses using the exact same syntax that one uses to define ordinary references and getters in classes.

But it’s not the exact same syntax.

- Ordinary refinement: `shared actual Type name = …;`
- Shortcut refinement: `name = …;`
- Ordinary declaration: `shared Type name = …;`

You can’t use the shortcut syntax to declare a non-refining declaration (you’ll get an error, “function or value is not defined”). The syntaxes are similar (because we value consistency), but not identical.

**Comment by jvasileff** [comment]
> I don’t think that’s a typo – the sentence makes sense to me as it is. With “or”, it seems weird to me: we’re already refining the superclass!

The quote is inaccurate. What's published is "or".

**Comment by lucaswerkmeister** [comment]
Fixed in #484 (@jvasileff merged it before I could fix the $483 to #483, that’s why you don’t see a mention).
